Fix css-loader configuration
after the upgrade of the module, we're getting an error when the webpack
runs, that basically says:

> Error: Can't resolve '/assets/images/govuk-crest.png' in '/tmp/build/f541ec31/repo/src/layouts'

We can fix that apparently, by simply disabling the URLs from the loader
as the actual functionality is already handled with the
`express-static-gzip` module.